### ISSUE TITLE
Can't register (price.change) events

### ISSUE THREAD

**Issue by grin** [Semantics3/semantics3-ruby#14]
I'm trying to run the following code:

```rb
params = {"type" => "price.change", "product" => {"sem3_id" => "2vQ7RG89dwU2wCccS0ESyq"}}

webhook_id = 'XXXXXXX'
endpoint = "webhooks/#{webhook_id}/events"

sem3 = Semantics3::Products.new(ENV['SEMANTICS3_KEY'], ENV['SEMANTICS3_SECRET'])
sem3.run_query(endpoint,"POST",params)
```

and that is throwing an error:
```
NoMethodError: undefined method `strip' for {"sem3_id"=>"2vQ7RG89dwU2wCccS0ESyq"}:Hash
from /Users/grin/.rbenv/versions/2.2.3/lib/ruby/2.2.0/net/http/header.rb:17:in `block in initialize_http_header'
```

which I tried to fix in my fork:  https://github.com/grin/semantics3-ruby/commit/96e89b31ef8b8fd8de0cc1b25a800386c78bf9d9

But then with the above fix I run into another error:
```
[7] pry(main)> eventObject = sem3.run_query(endpoint,"POST",params)
=> {"code"=>"OAuthError", "message"=>"OAuth Authentication Failed"}
```

so I then tried this in my fork: https://github.com/grin/semantics3-ruby/commit/7b3c2514ff1176219f49bd53950d8197ee9537fa

but it's still returning:
`{"code"=>"OAuthError", "message"=>"OAuth Authentication Failed"}`

Any ideas how I should fix this? Thanks.

I'm testing this with Ruby `2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]` and Rails 4.2.4

**Comment by vinothgopi** [comment]
@grin Are you facing issues with authentication only with webhooks or for any kind of queries from the ruby library?

**Comment by grin** [comment]
This is happening only with webhooks/events, other GET requests for products/search are working fine. So this seems like an issue with the POST request specifically.

**Comment by grin** [comment]
Even `sem3.run_query('webhooks', 'GET')` is working, only POST is returning that `OAuthError`

**Comment by vinothgopi** [comment]
@grin i've pushed a fix. Could you try building the library from source?

Here is the diff in case you want to try it in your fork: [https://github.com/Semantics3/semantics3-ruby/commit/60cd0261d3d4ddaf3506e31189bb2df9572fc53e](https://github.com/Semantics3/semantics3-ruby/commit/60cd0261d3d4ddaf3506e31189bb2df9572fc53e)

**Comment by grin** [comment]
That fixed it, thanks.
